databases:
  - name: tripleg-postgres
    databaseName: tripleg_db
    user: tripleg_user

services:
  - type: web
    name: tripleg-web
    env: python
    buildCommand: "./build.sh"
    startCommand: "cd TripleG && gunicorn config.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: tripleg-postgres
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4